package com.example.milista.ui.utils

fun getTranslatedText(text: String, language: String): String {
    val translations = mapOf(
        "Español (español)" to mapOf(
            "Buenos días" to "Buenos días",
            "Buenas tardes" to "Buenas tardes",
            "Buenas noches" to "Buenas noches",
            "Hoy en un vistazo" to "Hoy en un vistazo",
            "Tareas completadas" to "Tareas completadas",
            "Próximo evento" to "Próximo evento",
            "¡Que tengas un gran día!" to "¡Que tengas un gran día!",
            "Organiza tu jornada" to "Organiza tu jornada",
            "Próximos Avisos" to "Próximos Avisos",
            "Nuevo Recordatorio" to "Nuevo Recordatorio",
            "Toca para crear uno nuevo" to "Toca para crear uno nuevo",
            "Tus Listas" to "Tus Listas",
            "Agregar Nueva Lista" to "Agregar Nueva Lista",
            "Crea un nuevo espacio" to "Crea un nuevo espacio",
            "Mostrar recordatorios" to "Mostrar recordatorios",
            "Ocultar recordatorios" to "Ocultar recordatorios",
            "Calendario" to "Calendario",
            "Reloj" to "Reloj",
            "Notas" to "Notas",
            "Ajustes" to "Ajustes",
            "Quedan" to "Quedan",
            "Queda" to "Queda",
            "días" to "días",
            "y" to "y",
            "¡Es ahora!" to "¡Es ahora!",
            "Otro" to "Otro",
            "Trabajo" to "Trabajo",
            "Salud" to "Salud",
            "Compras" to "Compras",
            "Personal" to "Personal",
            "Mis Listas" to "Mis Listas",
            "Nueva Lista" to "Nueva Lista",
            "Nombre de la lista" to "Nombre de la lista",
            "Crear" to "Crear",
            "Cancelar" to "Cancelar",
            "Aplicando cambios" to "Aplicando cambios",
            "Nueva Tarea" to "Nueva Tarea",
            "¿Qué quieres hacer?" to "¿Qué quieres hacer?",
            "Guardar Tarea" to "Guardar Tarea",
            "Configurar Aviso" to "Configurar Aviso",
            "Personaliza tu aviso" to "Personaliza tu aviso",
            "Nombre del evento" to "Nombre del evento",
            "Seleccionar Emoji" to "Seleccionar Emoji",
            "Emoji seleccionado" to "Emoji seleccionado",
            "Elige un color:" to "Elige un color:",
            "Siguiente: Fecha" to "Siguiente: Fecha",
            "1. Selecciona la fecha" to "1. Selecciona la fecha",
            "Siguiente: Elegir Hora" to "Siguiente: Elegir Hora",
            "Volver a Personalizar" to "Volver a Personalizar",
            "2. Selecciona la hora" to "2. Selecciona la hora",
            "Guardar Evento" to "Guardar Evento",
            "Volver a Fecha" to "Volver a Fecha",
            "Elige un Emoji" to "Elige un Emoji",
            "Buscar emoji..." to "Buscar emoji...",
            "Cerrar" to "Cerrar",
            "Recientes" to "Recientes",
            "Caras" to "Caras",
            "Animales" to "Animales",
            "Naturaleza" to "Naturaleza",
            "Comida" to "Comida",
            "Actividad" to "Actividad",
            "Viajes" to "Viajes",
            "Objetos" to "Objetos",
            "Apariencia" to "Apariencia",
            "Tema de la app" to "Tema de la app",
            "Tipo de letra" to "Tipo de letra",
            "Tamaño de letra" to "Tamaño de letra",
            "General" to "General",
            "Idioma" to "Idioma",
            "Notificaciones" to "Notificaciones",
            "Avisos sonoros y vibración" to "Avisos sonoros y vibración",
            "Información" to "Información",
            "Versión de la app" to "Versión de la app",
            "Calificar app" to "Calificar app",
            "¡Danos 5 estrellas!" to "¡Danos 5 estrellas!",
            "Seleccionar Idioma" to "Seleccionar Idioma",
            "Volver" to "Volver",
            "Oscuro" to "Oscuro",
            "Claro" to "Claro",
            "Sistema" to "Sistema",
            "Pequeño" to "Pequeño",
            "Normal" to "Normal",
            "Grande" to "Grande",
            "Extra Grande" to "Extra Grande",
            "Alarma" to "Alarma",
            "Alarmas" to "Alarmas",
            "Mundial" to "Reloj mundial",
            "Temporizador" to "Temporizador",
            "Cronómetro" to "Cronómetro",
            "No hay alarmas" to "Sin alarmas",
            "Eliminar alarma" to "Eliminar alarma",
            "¿Deseas eliminar esta alarma?" to "¿Deseas eliminar esta alarma?",
            "Nueva Alarma" to "Añadir alarma",
            "Eventos para este día" to "Eventos para este día",
            "No hay eventos programados" to "No hay eventos programados",
            "No tienes listas aún" to "No tienes listas aún",
            "Ponle un nombre a tu nueva colección de tareas." to "Ponle un nombre a tu nueva colección de tareas.",
            "Ej: Compras, Trabajo..." to "Ej: Compras, Trabajo...",
            "¿Eliminar lista?" to "¿Eliminar lista?",
            "Se borrarán todas las tareas dentro de esta lista. Esta acción no se puede deshacer." to "Se borrarán todas las tareas dentro de esta lista. Esta acción no se puede deshacer.",
            "Eliminar" to "Eliminar",
            "Toca para ver tareas" to "Toca para ver tareas",
            "Pausado" to "Pausado",
            "Cumpleaños" to "Cumpleaños",
            "Diplomado" to "Diplomado",
            "Entrevista" to "Entrevista",
            "Doctor" to "Doctor",
            "Gimnasio" to "Gimnasio",
            "Examen" to "Examen",
            "Viaje" to "Viaje",
            "Pago" to "Pago",
            "Cena" to "Cena",
            "Reunión" to "Reunión",
            "Boda" to "Boda",
            "Concierto" to "Concierto",
            "Deporte" to "Deporte",
            "Limpieza" to "Limpieza",
            "Medicamento" to "Medicamento",
            "Cine" to "Cine",
            "Compra" to "Compra",
            "Cita" to "Cita",
            "L" to "L",
            "M" to "M",
            "X" to "X",
            "J" to "J",
            "V" to "V",
            "S" to "S",
            "D" to "D"
        ),
        "Inglés (English)" to mapOf(
            "Buenos días" to "Good morning",
            "Buenas tardes" to "Good afternoon",
            "Buenas noches" to "Good evening",
            "Hoy en un vistazo" to "Today at a glance",
            "Tareas completadas" to "Tasks completed",
            "Próximo evento" to "Next event",
            "¡Que tengas un gran día!" to "Have a great day!",
            "Organiza tu jornada" to "Organize your day",
            "Próximos Avisos" to "Upcoming Alerts",
            "Nuevo Recordatorio" to "New Reminder",
            "Toca para crear uno nuevo" to "Tap to create new",
            "Tus Listas" to "Your Lists",
            "Agregar Nueva Lista" to "Add New List",
            "Crea un nuevo espacio" to "Create a new space",
            "Mostrar recordatorios" to "Show reminders",
            "Ocultar recordatorios" to "Hide reminders",
            "Calendario" to "Calendar",
            "Reloj" to "Clock",
            "Notas" to "Notes",
            "Ajustes" to "Settings",
            "Quedan" to "Left",
            "Queda" to "Left",
            "días" to "days",
            "y" to "and",
            "¡Es ahora!" to "It's now!",
            "Otro" to "Other",
            "Trabajo" to "Work",
            "Salud" to "Health",
            "Compras" to "Shopping",
            "Personal" to "Personal",
            "Mis Listas" to "My Lists",
            "Nueva Lista" to "New List",
            "Nombre de la lista" to "List Name",
            "Crear" to "Create",
            "Cancelar" to "Cancel",
            "Aplicando cambios" to "Applying changes",
            "Nueva Tarea" to "New Task",
            "¿Qué quieres hacer?" to "What do you want to do?",
            "Guardar Tarea" to "Save Task",
            "Configurar Aviso" to "Set Up Alert",
            "Personaliza tu aviso" to "Customize your alert",
            "Nombre del evento" to "Event Name",
            "Seleccionar Emoji" to "Select Emoji",
            "Emoji seleccionado" to "Emoji selected",
            "Elige un color:" to "Choose a color:",
            "Siguiente: Fecha" to "Next: Date",
            "1. Selecciona la fecha" to "1. Select the date",
            "Siguiente: Elegir Hora" to "Next: Choose Time",
            "Volver a Personalizar" to "Back to Customize",
            "2. Selecciona la hora" to "2. Select the time",
            "Guardar Evento" to "Save Event",
            "Volver a Fecha" to "Back to Date",
            "Elige un Emoji" to "Choose an Emoji",
            "Buscar emoji..." to "Search emoji...",
            "Cerrar" to "Close",
            "Recientes" to "Recent",
            "Caras" to "Faces",
            "Animales" to "Animals",
            "Naturaleza" to "Nature",
            "Comida" to "Food",
            "Actividad" to "Activity",
            "Viajes" to "Travel",
            "Objetos" to "Objects",
            "Apariencia" to "Appearance",
            "Tema de la app" to "App Theme",
            "Tipo de letra" to "Font Type",
            "Tamaño de letra" to "Font Size",
            "General" to "General",
            "Idioma" to "Language",
            "Notificaciones" to "Notifications",
            "Avisos sonoros y vibración" to "Sound alerts and vibration",
            "Información" to "Information",
            "Versión de la app" to "App Version",
            "Calificar app" to "Rate app",
            "¡Danos 5 estrellas!" to "Give us 5 stars!",
            "Seleccionar Idioma" to "Select Language",
            "Volver" to "Back",
            "Oscuro" to "Dark",
            "Claro" to "Light",
            "Sistema" to "System",
            "Pequeño" to "Small",
            "Normal" to "Normal",
            "Grande" to "Large",
            "Extra Grande" to "Extra Large",
            "Alarma" to "Alarm",
            "Alarmas" to "Alarms",
            "Mundial" to "World clock",
            "Temporizador" to "Timer",
            "Cronómetro" to "Stopwatch",
            "No hay alarmas" to "No alarms",
            "Eliminar alarma" to "Delete alarm",
            "¿Deseas eliminar esta alarma?" to "Delete this alarm?",
            "Nueva Alarma" to "Add alarm",
            "Eventos para este día" to "Events for this day",
            "No hay eventos programados" to "No scheduled events",
            "No tienes listas aún" to "You don't have lists yet",
            "Ponle un nombre a tu nueva colección de tareas." to "Give your new task collection a name.",
            "Ej: Compras, Trabajo..." to "Ex: Shopping, Work...",
            "¿Eliminar lista?" to "Delete list?",
            "Se borrarán todas las tareas dentro de esta lista. Esta acción no se puede deshacer." to "All tasks within this list will be deleted. This action cannot be undone.",
            "Eliminar" to "Delete",
            "Toca para ver tareas" to "Tap to view tasks",
            "Pausado" to "Paused",
            "Cumpleaños" to "Birthday",
            "Diplomado" to "Diploma",
            "Entrevista" to "Interview",
            "Doctor" to "Doctor",
            "Gimnasio" to "Gym",
            "Examen" to "Exam",
            "Viaje" to "Travel",
            "Pago" to "Payment",
            "Cena" to "Dinner",
            "Reunión" to "Meeting",
            "Boda" to "Wedding",
            "Concierto" to "Concert",
            "Deporte" to "Sport",
            "Limpieza" to "Cleaning",
            "Medicamento" to "Medicine",
            "Cine" to "Cinema",
            "Compra" to "Purchase",
            "Cita" to "Appointment",
            "L" to "M",
            "M" to "T",
            "X" to "W",
            "J" to "T",
            "V" to "F",
            "S" to "S",
            "D" to "S"
        )
    )
    return translations[language]?.get(text) ?: text
}

fun getLocaleCode(language: String): String {
    return when (language) {
        "Español (español)" -> "es"
        "Inglés (English)" -> "en"
        "Portugués (português)" -> "pt"
        "Japonés (日本語)" -> "ja"
        "Coreano (한국인)" -> "ko"
        "Ruso (Pусский)" -> "ru"
        "Árabe (العربية)" -> "ar"
        "Mapudungun (Mapudungun)" -> "arn"
        else -> "es"
    }
}
